# Generated by Django 5.1.7 on 2025-03-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartIteam',
            new_name='CartItem',
        ),
    ]
